using Core.Models;

namespace CondominiosApi.Features.ListCondominios;

public sealed record ListResponse(
    IReadOnlyCollection<CondominioItem> Items,
    int PaginaAtual,
    int ItensPorPagina,
    int TotalItens,
    int TotalPaginas);

public sealed record CondominioItem(
    int CodCondom,
    string? NomeCondom,
    string? Ativo,
    string? Cnpj,
    string? Cei,
    string? InscrMunicip,
    int? QtdBlocos,
    int? QtdUnidades,
    decimal? TotalFracao,
    int? DiaVencDoc,
    int? DataInicioAdm,
    int? DataDistrato,
    string? MotivoDistrato,
    string? Assessor,
    string? Filial,
    string? Agencia,
    string? Sindico,
    string? SubSindico,
    string? Conselheiro,
    string? Gestor,
    string? ConselhoFiscal,
    string? ConselhoConsultivo,
    string? ConselhoSuplente,
    string? TipoCondominio,
    string? TipoCategoria,
    DateTime? DtAlteracao,
    string? TipoLograd,
    string? Lograd,
    string? Numero,
    string? Bairro,
    string? Cidade,
    string? Cep8Log,
    string? Uf,
    string? CodPessoaSindico,
    string? NomeSindico,
    string? CpfDocnpj,
    string? CondGarantido,
    string? TipoConta,
    string? ObsCobranca,
    string? Garantidora)
{
    public static CondominioItem FromCondominio(Condominio condominio) => new(
        condominio.CodCondom,
        condominio.NomeCondom,
        condominio.Ativo,
        condominio.Cnpj,
        condominio.Cei,
        condominio.InscrMunicip,
        condominio.QtdBlocos,
        condominio.QtdUnidades,
        condominio.TotalFracao,
        condominio.DiaVencDoc,
        condominio.DataInicioAdm,
        condominio.DataDistrato,
        condominio.MotivoDistrato,
        condominio.Assessor,
        condominio.Filial,
        condominio.Agencia,
        condominio.Sindico,
        condominio.SubSindico,
        condominio.Conselheiro,
        condominio.Gestor,
        condominio.ConselhoFiscal,
        condominio.ConselhoConsultivo,
        condominio.ConselhoSuplente,
        condominio.TipoCondominio,
        condominio.TipoCategoria,
        condominio.DtAlteracao,
        condominio.TipoLograd,
        condominio.Lograd,
        condominio.Numero,
        condominio.Bairro,
        condominio.Cidade,
        condominio.Cep8Log,
        condominio.Uf,
        condominio.CodPessoaSindico,
        condominio.NomeSindico,
        condominio.CpfDocnpj,
        condominio.CondGarantido,
        condominio.TipoConta,
        condominio.ObsCobranca,
        condominio.Garantidora);
}
